version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'WatchOurMovieDB'
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
  app:
    image: angular/frontend
    build: ./frontend
    command: "npm run start -- --host=0.0.0.0 --port=8080 --configuration 'production' "
    ports:
      - 8080:8080
  back:
    image: fastapi/backend
    build: ./backend
    ports:
      - 8000:8000
volumes:
  db: