version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - networkName
    volumes:
      - db:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
  app:
    image: angular/frontend
    build: ./frontend
    command: "npm run start -- --host=0.0.0.0 --port=8080 --configuration 'production' "
    ports:
      - 8080:8080
    networks:
      - networkName
    env_file:
      - .env
    depends_on:
      - back
  back:
    image: fastapi/backend
    build: ./backend
    ports:
      - 8000:8000
    networks:
      - networkName
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
    depends_on:
      - mysql
    restart: on-failure
volumes:
  db:
networks:
  networkName:
